version: '3'
services:
  es:
    image: eventstore/eventstore:latest
    ports:
      - "2113:2113"
      - "1113:1113"
    environment:
      - EVENTSTORE_RUN_PROJECTIONS=System
      - EVENTSTORE_START_STANDARD_PROJECTIONS=True
