version: 2
jobs:
  build:
    working_directory: /tmp/build
    docker:
      - image: spikerlabs/scala-sbt:scala-2.12.2-sbt-0.13.13
    steps:
      - checkout
      - run:
          name: install git
          command: apk add --no-cache git
      - run:
          name: Run tests
          command: sbt "api/test"
      - run:
          name: Build API Client and store it as an artifact
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then

              # create folders for the artifacts
              mkdir /tmp/api-client-js
              mkdir /tmp/api-client-js/lib

              # build
              sbt "apiClientJs/fullOptJS"
              cd api-client-js
              cp -f target/scala-2.12/api-client-js-opt.js /tmp/api-client-js/lib/index.js
              cd ..

              # store version
              sbt version
              sbt -no-colors --info ";project apiClientJs; version" | tail -1 | sed 's/\[info\][^0-9a-zA-Z]*//' | sed 's/\-[a-zA-Z].*$//' > /tmp/version

              # prepare artifacts
              cd api-client-js/src/main/resources
              sed "s/%%VERSION%%/$(cat "/tmp/version")/" package.template.json > /tmp/api-client-js/package.json
              cp index.js   /tmp/api-client-js/index.js
              cp index.d.ts /tmp/api-client-js/index.d.ts
              cd /tmp
              tar -zcvf api-client-js.tar.gz api-client-js

              # invoke npm package build
              curl --user ${CIRCLE_API_TOKEN}: \
                --data build_parameters[CIRCLE_JOB]=publish_api_client \
                --data build_parameters[BUILD_NUM_WITH_ARTIFACTS]=${CIRCLE_BUILD_NUM} \
                --data revision=$CIRCLE_SHA1 \
                https://circleci.com/api/v1.1/project/github/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/tree/${CIRCLE_BRANCH}
            fi
      - store_artifacts:
          path: /tmp/api-client-js.tar.gz
          destination: api-client-js.tar.gz
      - deploy:
          name: Publish API image to Docker Hub
          command: |
            #if [ "${CIRCLE_BRANCH}" == "master" ]; then
            #  apk add --no-cache docker
            #  docker login -u ${DOCKER_LOGIN} -p ${DOCKER_PASSWORD}
            #  sbt docker:publish
            #fi
  publish_api_client:
    working_directory: /
    docker:
      - image: node:6
    steps:
      - run:
          name: Get artifacts from original build
          command: |
            export GET_ARTIFACT_URL=https://circleci.com/api/v1.1/project/github/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/${BUILD_NUM_WITH_ARTIFACTS}/artifacts\?circle-token\=${CIRCLE_API_TOKEN}
            curl $(curl ${GET_ARTIFACT_URL} | grep -o 'https://[^"]*')\?circle-token\=${CIRCLE_API_TOKEN} > api-client-js.tar.gz
            tar -xf api-client-js.tar.gz
      - run:
          name: Pack the npm package
          command: cd api-client-js && npm pack
      - run:
          name: Authenticate with NPM
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run:
          name: Publish npm package to repository
          command: npm push $(ls api-client-js/scala-fun-client-*.tgz)